/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooterComponent: typeof import('./src/components/appFooterComponent.vue')['default']
    AppHeaderComponent: typeof import('./src/components/appHeaderComponent.vue')['default']
    DefaultLayout: typeof import('./src/components/defaultLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
